### ISSUE TITLE
Weird cursor respositioning after completion fail

### ISSUE THREAD

**Issue by edygar** [lfilho/dotfiles#16]
When <kbd>tab</kbd> is pressed and no matches are found, cursor goes to wrong line.

![captura de tela 2017-05-30 as 13 59 58](https://cloud.githubusercontent.com/assets/566280/26584514/ee145e76-4540-11e7-8a03-da59b9de7dac.png)

**Comment by lfilho** [comment]
This doesn't happen in my install. Probably is due the auto-suggestions module you have turned on? Could you test disabling it, reloading your terminal and trying again?

**Comment by lfilho** [comment]
![image](https://cloud.githubusercontent.com/assets/282756/26586123/8383ff90-454e-11e7-8869-55b4b38e2a7f.png)

**Comment by edygar** [comment]
I've tried, it isn't related, this cursor still goes to the previous line, at the right column.

**Comment by lfilho** [comment]
Are you sure you didn't have the auto-suggestions module enabled / loaded? Try forcing its unload, quitting iTerm and opening it again.

Again, it works for me (master branch). After typing `qwerty` and `tab`, the cursor stays after `y`.

**Comment by lfilho** [comment]
And I never had the problem before (and I'm using tab all the time of course). So I'm pretty sure it must be something on your end 😇

**Comment by edygar** [comment]
It kind of was… *kind of* … https://github.com/sorin-ionescu/prezto/issues/1245

**Comment by lfilho** [comment]
Haha what do you mean kind of?? :-D
So is it working now? Have you upgraded or downgraded your zsh? Mine is `5.3.1` and it is working fine.

Thanks for investigating it.

**Comment by edygar** [comment]
I said it was kind of on my side. It happened because I already had a zsh installed and it was behind a few versions. I think we could point `--HEAD` at `brewfile` for zsh, almost sure Mac includes a lower version.

**Comment by lfilho** [comment]
I think `--HEAD` is dangerous as it may included unstable code. I think the problem was that you didn't run `brew update` in a while...

**Comment by edygar** [comment]
I've just clean installed my OS X, so I thought didn't need to.
