### ISSUE TITLE
Linux Support Efforts

### ISSUE THREAD

**Issue by lfilho** [lfilho/dotfiles#2]
Just a quick dump of some things I'm observing while trying to install it on Linux, in order to start supporting it:

1) Installing vim-gnome via apt-get will install vim with lua support (as of this writing, version  7.4.52). Will also install ruby as dependency for us (Ruby is required by YADR either way).

**Comment by edygar** [comment]
Related to this issue, isn't python a better option for managing and installing dependencies rather ruby? 
Python has a broader availability among *nix systems.

**Comment by lfilho** [comment]
Ruby is chosen one because the original repo (the one I forked this one from) aims OSX firstly. And ruby comes with OSX out of the box, so that means one less dependency to have to install.

Additionally, ruby is pretty much available and easily installable everywhere, just like python too.

If this repo was primarily aimed at Linux systems, then I guess python would indeed make more sense.

**Comment by edygar** [comment]
I understand though my points are still valid…  =P
> “If a feature is sometimes dangerous, and there is a better option, then always use the better option.” ~ Douglas Crockford
I'm gonna try rewrite and PR to the original repo.

**Comment by lfilho** [comment]
And why is python "better" in this case?

**Comment by edygar** [comment]
I'm talking about availability, so a wider range of OSs comes with Python included, while ruby is available from factory only on OSX.  So, why depend on something that maybe should be installed while we can use something almost to be there?

**Comment by lfilho** [comment]
As I said... It comes down to the original repo owner's OS. Which also happens to be mine. Also, his main developing language is Ruby, so it makes total sense for his case.

I can't test stuff on linux nor have the time to mess around with virtual machines and etc. But I do have OSX and ruby. So for me it sounds better just to test with ruby, and then, on a linux machine run a `apt-get install ruby` and you're done.

But, go for it! PRs are always welcome.

**Comment by lfilho** [comment]
I have just added Docker support (both here and on upstream). Feel free to check it out :-)

**Comment by lfilho** [comment]
I'm closing this issue as we have the Docker image now. All feature requests or bugs should come in their on issue or pull request now... Keep the contributions coming, please :-) 👍
