### ISSUE TITLE
NVim ,b conflict

### ISSUE THREAD

**Issue by edygarOliveira** [lfilho/dotfiles#28]
[CtrlP binding](https://github.com/lfilho/dotfiles/blob/master/nvim/settings/plugin-ctrlp.vim#L29) <kbd>,</kbd>+<kbd>b</kbd> conflicts with [camelcasemotion's](https://github.com/lfilho/dotfiles/blob/master/nvim/plugins/improvements.vim#L30) (see [here](https://github.com/vim-scripts/camelcasemotion/blob/master/plugin/camelcasemotion.vim#L161-L165))

**Comment by lfilho** [comment]
I've done some research in order to find a came case plugin that would allow us to configure which key to use for camel case motion.

Then I found this: https://github.com/chaoren/vim-wordmotion 

It does allow that, but that gave me another idea: what if we make camel case motion the default one?

**Comment by lfilho** [comment]
I have created a branch `new-camel-case-motion` and will test this plugin for a while and see how it feels.

I think it makes sense to make `w` and friends be camel case aware by default, don't you think?

**Comment by edygar** [comment]
As we spoke earlier: It might not be so good, as we are adviced to not overwrite default VIM bindings, so the best solution would be to change ctrlP buffer to `,ob`

**Comment by lfilho** [comment]
Done
