### ISSUE TITLE
prompt lfilho slow

### ISSUE THREAD

**Issue by yjlintw** [lfilho/dotfiles#32]
I like the theming of prompt lfilho, but it is a little lag on a git repo comparing to the powerline theme. Do you know which part might cause this latency? Thanks.

**Comment by lfilho** [comment]
Hi @yjlintw , thanks for your compliment. Glad you like it.

Unfortunately I don't why it might be lagging. I just copied and pasted from another theme in the upstream repo and tweaked the colors and characters and some positioning.

Do you think you could help me improve it?

**Comment by yjlintw** [comment]
I'll look into that when I have time, though I'm not sure if I am capable doing that. My guess is that it might be related to grabbing information from git repo.

**Comment by yjlintw** [comment]
I have also documented what extra steps that I need to do to install these dotfiles on Ubuntu here.
https://github.com/yjlintw/dotfiles/issues/1

Some of them might not be suitable for this repo. (For example, I'm using YCM instead of deoplete)

**Comment by lfilho** [comment]
Hey @yjlintw coming back here after so long time... Did you have time to investigate was my prompt was slow for you? I just switched around different themes but they all seemed equally fast.

If you could provide a way to reproduce the lag...

**Comment by yjlintw** [comment]
Sorry, I wasn't doing that. To me, I think it is probably a few hundred ms latency, and it only happens when the current path is a git repo. Other theme, for example agnoster response immediately when I press enter.

**Comment by lfilho** [comment]
Can you try the branch https://github.com/lfilho/dotfiles/tree/powerlevel9k and see if it's any better? It's a different theme i've been playing with

**Comment by lfilho** [comment]
Hey I didn't hear back from you. I'll assume the new theme works better for you now and the problem is resolved. Feel free to reopen this otherwise
