### ISSUE TITLE
Neovim Xenial not available causes Dockerfile to fail.

### ISSUE THREAD

**Issue by daxgames** [lfilho/dotfiles#33]
I know this is not your issue.  Just raising awareness.

![image](https://user-images.githubusercontent.com/7318053/91660837-2b4a9400-eaa6-11ea-82c5-2f7b270a7dd4.png)

I changed the Dockerfile to use the unstable neovim ppa and the neovim install is successful and the docker compose run succeeds.

**Comment by lfilho** [comment]
Thank you, I'll try to make some linux-related improvement and also fix the build soon!
