### ISSUE TITLE
Enhancement on documentation (README.md) for newbies

### ISSUE THREAD

**Issue by rfontoura** [lfilho/dotfiles#7]
Hi, Luiz!

Now that I've installed you custom Zsh on a clean machine, and without your help, I think I can contribute to help newbies on zsh installation on a clean newly-installed Linux OS. For those not familiar with Ruby on Rails nor `rake`, here's my sugestion to a simple step-by-step installation guide:

1. Make sure you have `zsh` installed on your machine (default location is `/bin/zsh`). Type `zsh --version` to see if you have it. If not, install it running the command `sudo apt-get install zsh`
1. Make sure you have `vim` installed. If not, install it with `sudo apt-get install vim`
1. Run the installation script running ```sh -c "`curl -fsSL https://raw.githubusercontent.com/lfilho/dotfiles/master/install.sh`"```
1. When the installation program ask for saving Vim file, answer yes
1. If asked, provide your superuser password
1. Configure your terminal program to point the command to zsh (default `/bin/zsh`)
1. Restart you Terminal
1. You're done.

**Comment by lfilho** [comment]
Hey @rfontoura Thanks man! Could open a PR to fit those into the README then? Maybe an extra section for Linux users? (because most of what you wrote happens automatically for OSX users already).

Also, on step 4, do we need to save it? I don't think we do...

**Comment by rfontoura** [comment]
Well, on step 4, I only answered Yes until now, just to be sure that everything will be fine :sweat_smile: . Don't know if I really need to save.

OK, I'll create a PR with these steps, except step 4.

**Comment by lfilho** [comment]
Also, there's Homebrew (OSX's best package manager) for Linux too: http://linuxbrew.sh/

I think we a Linux user install it, all the other installation steps might just work! (`brew insta....`). If you have the time/interest, that would be a nice thing! :)

Thanks again for you contribution

**Comment by rfontoura** [comment]
Humm... nice tip, @lfilho. I'll bookmark it to see later. Thanks!

**Comment by rfontoura** [comment]
I think we can close this issue, right?

**Comment by lfilho** [comment]
Yes, thanks. Closing it now.

**Tip**: if you make a commit and include `closes #7` or `fixes #7` or `close #7` or `fix #7`, it will automatically close the issue with that number when it gets merged to master ;)

Thanks again!

**Comment by rfontoura** [comment]
Hum... that's right. We're using these keywords on DE to close the issues. Forgot to use it here. Thanks, man.
